# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74453f3137b7ad264c53cb1af4a464ab999b8dc587d4f1937c4f48ce968daad0023191e71e419605812986c5683552521b79cb44fb08033c0e391fc546728417

test:
  secret_key_base: 2bef2240d2da655d478ac78cf97c05b5140210f29f90e8b4c4388a29920e2fbbafe973e9d52248856c1efa46ffda9f99cd7661d9a2f31890d02ddda53e03cc2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
